### ISSUE TITLE
Library doesn't work

### ISSUE THREAD

**Issue by Metalism666** [Snudgee/LIGHT-UI#13]
![SharedScreenshot](https://user-images.githubusercontent.com/87187521/140266874-033c74db-4ae3-466b-9095-1cdfe3e556ef.jpg)

i followed the guide and installed it
is i use newest version steamfriendpatcher 0.1.4 cause it happened？
by the way friends UI in steam still default too

**Comment by Metalism666** [comment]
its done，its ‘’steam beta test‘’ in setting cause it，i close it and everything work fine now！ ：）

**Comment by Snudgee** [comment]
Great 😃
